name: Check and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Generate package-lock
        run: npm run lockfile

      - name: Commit package-lock
        run: |
          if git diff --quiet -- package-lock.json; then
            echo "package-lock.json is already up to date."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: generate package-lock.json"
            git push
          fi

      - name: Install dependencies
        run: npm ci

      - name: Check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          BASE_PATH: /${{ github.event.repository.name }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
